#ifndef wolfsp_appvar_include_file
#define wolfsp_appvar_include_file

#ifdef __cplusplus
extern "C" {
#endif

#define wolfsp_appvar_size 3520
#define sizeof_global_palette 168
#define global_palette (wolfsp_appvar[0])
#define sprites_palette_offset 0
#define strip1_width 1
#define strip1_height 64
#define wolfsp_sprites_strip1_compressed_index 1
#define strip1_compressed wolfsp_appvar[1]
#define strip2_width 1
#define strip2_height 64
#define wolfsp_sprites_strip2_compressed_index 2
#define strip2_compressed wolfsp_appvar[2]
#define strip3_width 1
#define strip3_height 64
#define wolfsp_sprites_strip3_compressed_index 3
#define strip3_compressed wolfsp_appvar[3]
#define strip4_width 1
#define strip4_height 64
#define wolfsp_sprites_strip4_compressed_index 4
#define strip4_compressed wolfsp_appvar[4]
#define strip5_width 1
#define strip5_height 64
#define wolfsp_sprites_strip5_compressed_index 5
#define strip5_compressed wolfsp_appvar[5]
#define strip6_width 1
#define strip6_height 64
#define wolfsp_sprites_strip6_compressed_index 6
#define strip6_compressed wolfsp_appvar[6]
#define strip7_width 1
#define strip7_height 64
#define wolfsp_sprites_strip7_compressed_index 7
#define strip7_compressed wolfsp_appvar[7]
#define strip8_width 1
#define strip8_height 64
#define wolfsp_sprites_strip8_compressed_index 8
#define strip8_compressed wolfsp_appvar[8]
#define strip9_width 1
#define strip9_height 64
#define wolfsp_sprites_strip9_compressed_index 9
#define strip9_compressed wolfsp_appvar[9]
#define strip10_width 1
#define strip10_height 64
#define wolfsp_sprites_strip10_compressed_index 10
#define strip10_compressed wolfsp_appvar[10]
#define strip11_width 1
#define strip11_height 64
#define wolfsp_sprites_strip11_compressed_index 11
#define strip11_compressed wolfsp_appvar[11]
#define strip12_width 1
#define strip12_height 64
#define wolfsp_sprites_strip12_compressed_index 12
#define strip12_compressed wolfsp_appvar[12]
#define strip13_width 1
#define strip13_height 64
#define wolfsp_sprites_strip13_compressed_index 13
#define strip13_compressed wolfsp_appvar[13]
#define strip14_width 1
#define strip14_height 64
#define wolfsp_sprites_strip14_compressed_index 14
#define strip14_compressed wolfsp_appvar[14]
#define strip15_width 1
#define strip15_height 64
#define wolfsp_sprites_strip15_compressed_index 15
#define strip15_compressed wolfsp_appvar[15]
#define strip16_width 1
#define strip16_height 64
#define wolfsp_sprites_strip16_compressed_index 16
#define strip16_compressed wolfsp_appvar[16]
#define strip17_width 1
#define strip17_height 64
#define wolfsp_sprites_strip17_compressed_index 17
#define strip17_compressed wolfsp_appvar[17]
#define strip18_width 1
#define strip18_height 64
#define wolfsp_sprites_strip18_compressed_index 18
#define strip18_compressed wolfsp_appvar[18]
#define strip19_width 1
#define strip19_height 64
#define wolfsp_sprites_strip19_compressed_index 19
#define strip19_compressed wolfsp_appvar[19]
#define strip20_width 1
#define strip20_height 64
#define wolfsp_sprites_strip20_compressed_index 20
#define strip20_compressed wolfsp_appvar[20]
#define strip21_width 1
#define strip21_height 64
#define wolfsp_sprites_strip21_compressed_index 21
#define strip21_compressed wolfsp_appvar[21]
#define strip22_width 1
#define strip22_height 64
#define wolfsp_sprites_strip22_compressed_index 22
#define strip22_compressed wolfsp_appvar[22]
#define strip23_width 1
#define strip23_height 64
#define wolfsp_sprites_strip23_compressed_index 23
#define strip23_compressed wolfsp_appvar[23]
#define strip24_width 1
#define strip24_height 64
#define wolfsp_sprites_strip24_compressed_index 24
#define strip24_compressed wolfsp_appvar[24]
#define strip25_width 1
#define strip25_height 64
#define wolfsp_sprites_strip25_compressed_index 25
#define strip25_compressed wolfsp_appvar[25]
#define strip26_width 1
#define strip26_height 64
#define wolfsp_sprites_strip26_compressed_index 26
#define strip26_compressed wolfsp_appvar[26]
#define strip27_width 1
#define strip27_height 64
#define wolfsp_sprites_strip27_compressed_index 27
#define strip27_compressed wolfsp_appvar[27]
#define strip28_width 1
#define strip28_height 64
#define wolfsp_sprites_strip28_compressed_index 28
#define strip28_compressed wolfsp_appvar[28]
#define strip29_width 1
#define strip29_height 64
#define wolfsp_sprites_strip29_compressed_index 29
#define strip29_compressed wolfsp_appvar[29]
#define strip30_width 1
#define strip30_height 64
#define wolfsp_sprites_strip30_compressed_index 30
#define strip30_compressed wolfsp_appvar[30]
#define strip31_width 1
#define strip31_height 64
#define wolfsp_sprites_strip31_compressed_index 31
#define strip31_compressed wolfsp_appvar[31]
#define strip32_width 1
#define strip32_height 64
#define wolfsp_sprites_strip32_compressed_index 32
#define strip32_compressed wolfsp_appvar[32]
#define strip33_width 1
#define strip33_height 64
#define wolfsp_sprites_strip33_compressed_index 33
#define strip33_compressed wolfsp_appvar[33]
#define strip34_width 1
#define strip34_height 64
#define wolfsp_sprites_strip34_compressed_index 34
#define strip34_compressed wolfsp_appvar[34]
#define strip35_width 1
#define strip35_height 64
#define wolfsp_sprites_strip35_compressed_index 35
#define strip35_compressed wolfsp_appvar[35]
#define strip36_width 1
#define strip36_height 64
#define wolfsp_sprites_strip36_compressed_index 36
#define strip36_compressed wolfsp_appvar[36]
#define strip37_width 1
#define strip37_height 64
#define wolfsp_sprites_strip37_compressed_index 37
#define strip37_compressed wolfsp_appvar[37]
#define strip38_width 1
#define strip38_height 64
#define wolfsp_sprites_strip38_compressed_index 38
#define strip38_compressed wolfsp_appvar[38]
#define strip39_width 1
#define strip39_height 64
#define wolfsp_sprites_strip39_compressed_index 39
#define strip39_compressed wolfsp_appvar[39]
#define strip40_width 1
#define strip40_height 64
#define wolfsp_sprites_strip40_compressed_index 40
#define strip40_compressed wolfsp_appvar[40]
#define strip41_width 1
#define strip41_height 64
#define wolfsp_sprites_strip41_compressed_index 41
#define strip41_compressed wolfsp_appvar[41]
#define strip42_width 1
#define strip42_height 64
#define wolfsp_sprites_strip42_compressed_index 42
#define strip42_compressed wolfsp_appvar[42]
#define strip43_width 1
#define strip43_height 64
#define wolfsp_sprites_strip43_compressed_index 43
#define strip43_compressed wolfsp_appvar[43]
#define strip44_width 1
#define strip44_height 64
#define wolfsp_sprites_strip44_compressed_index 44
#define strip44_compressed wolfsp_appvar[44]
#define strip45_width 1
#define strip45_height 64
#define wolfsp_sprites_strip45_compressed_index 45
#define strip45_compressed wolfsp_appvar[45]
#define strip46_width 1
#define strip46_height 64
#define wolfsp_sprites_strip46_compressed_index 46
#define strip46_compressed wolfsp_appvar[46]
#define strip47_width 1
#define strip47_height 64
#define wolfsp_sprites_strip47_compressed_index 47
#define strip47_compressed wolfsp_appvar[47]
#define strip48_width 1
#define strip48_height 64
#define wolfsp_sprites_strip48_compressed_index 48
#define strip48_compressed wolfsp_appvar[48]
#define strip49_width 1
#define strip49_height 64
#define wolfsp_sprites_strip49_compressed_index 49
#define strip49_compressed wolfsp_appvar[49]
#define strip50_width 1
#define strip50_height 64
#define wolfsp_sprites_strip50_compressed_index 50
#define strip50_compressed wolfsp_appvar[50]
#define strip51_width 1
#define strip51_height 64
#define wolfsp_sprites_strip51_compressed_index 51
#define strip51_compressed wolfsp_appvar[51]
#define strip52_width 1
#define strip52_height 64
#define wolfsp_sprites_strip52_compressed_index 52
#define strip52_compressed wolfsp_appvar[52]
#define strip53_width 1
#define strip53_height 64
#define wolfsp_sprites_strip53_compressed_index 53
#define strip53_compressed wolfsp_appvar[53]
#define strip54_width 1
#define strip54_height 64
#define wolfsp_sprites_strip54_compressed_index 54
#define strip54_compressed wolfsp_appvar[54]
#define strip55_width 1
#define strip55_height 64
#define wolfsp_sprites_strip55_compressed_index 55
#define strip55_compressed wolfsp_appvar[55]
#define strip56_width 1
#define strip56_height 64
#define wolfsp_sprites_strip56_compressed_index 56
#define strip56_compressed wolfsp_appvar[56]
#define strip57_width 1
#define strip57_height 64
#define wolfsp_sprites_strip57_compressed_index 57
#define strip57_compressed wolfsp_appvar[57]
#define strip58_width 1
#define strip58_height 64
#define wolfsp_sprites_strip58_compressed_index 58
#define strip58_compressed wolfsp_appvar[58]
#define strip59_width 1
#define strip59_height 64
#define wolfsp_sprites_strip59_compressed_index 59
#define strip59_compressed wolfsp_appvar[59]
#define strip60_width 1
#define strip60_height 64
#define wolfsp_sprites_strip60_compressed_index 60
#define strip60_compressed wolfsp_appvar[60]
#define strip61_width 1
#define strip61_height 64
#define wolfsp_sprites_strip61_compressed_index 61
#define strip61_compressed wolfsp_appvar[61]
#define strip62_width 1
#define strip62_height 64
#define wolfsp_sprites_strip62_compressed_index 62
#define strip62_compressed wolfsp_appvar[62]
#define strip63_width 1
#define strip63_height 64
#define wolfsp_sprites_strip63_compressed_index 63
#define strip63_compressed wolfsp_appvar[63]
#define strip64_width 1
#define strip64_height 64
#define wolfsp_sprites_strip64_compressed_index 64
#define strip64_compressed wolfsp_appvar[64]
#define lowerScreenHUD1_width 160
#define lowerScreenHUD1_height 40
#define wolfsp_sprites_lowerScreenHUD1_compressed_index 65
#define lowerScreenHUD1_compressed wolfsp_appvar[65]
#define lowerScreenHUD2_width 160
#define lowerScreenHUD2_height 40
#define wolfsp_sprites_lowerScreenHUD2_compressed_index 66
#define lowerScreenHUD2_compressed wolfsp_appvar[66]
#define pistol1_width 64
#define pistol1_height 64
#define wolfsp_sprites_pistol1_compressed_index 67
#define pistol1_compressed wolfsp_appvar[67]
#define wolfsp_entries_num 68
extern unsigned char *wolfsp_appvar[68];
unsigned char wolfsp_init(void);

#ifdef __cplusplus
}
#endif

#endif
